### ISSUE TITLE
Implement health check path for ELB

### ISSUE THREAD

**Issue by git823** [ykhr53/bmo#3]
Return 200 to health check requests by ELB.

**Comment by git823** [comment]
ここに Handle を足して、Handler を別途定義するような感じでしょうか。
https://github.com/ykhr53/bmo/blob/fe433b2db9dcb30c7231664b96b1a60e12fe8bdf/bmo.go#L118-L123

**Comment by ykhr53** [comment]
Thank you for the request! It's totally acceptable. Going to add "ToDo" section.

**Comment by ykhr53** [comment]
Added to README.
https://github.com/ykhr53/bmo/pull/4

Going to close this issue.

**Comment by ykhr53** [comment]
I think I should manage "ToDo" list on issue. So reopen it.

**Comment by ykhr53** [comment]
By this commit, you can accept HTTP health check from ALB by `/health` path.
